Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/xenial64"
   config.vm.network "forwarded_port", guest: 80, host: 8081
   config.vm.define :titan do |titan|
      titan.vm.provider :virtualbox do |v|
         v.name = "titan"
         v.customize ["modifyvm", :id, "--memory", "1024", "--cpus", 1]
      end
      titan.vm.network :public_network
      titan.vm.hostname = "titan"
      titan.vm.provision :shell, :path => "setup-titan.sh"
   end
end
